-- Baseline: jarvis-notifications at alembic head 002, translated from the live dev DB on the
-- MacBook Pro. See docs/schema/notifications.md. The service has no settings table.
-- Legacy timestamps were naive `timestamp` written with datetime.utcnow (UTC); stored as
-- ISO-8601 UTC TEXT. Ids are UUID strings generated by the app.
-- ORM-side defaults (is_active, is_read, the counters) are promoted to DB defaults.

-- +goose Up

CREATE TABLE notifications_device_tokens (
    id           TEXT    PRIMARY KEY,
    user_id      INTEGER NOT NULL,
    household_id TEXT    NOT NULL,
    push_token   TEXT    NOT NULL,
    device_type  TEXT    NOT NULL, -- "ios" | "android" (not enforced by legacy)
    device_name  TEXT,
    is_active    INTEGER NOT NULL DEFAULT 1,
    last_used_at TEXT,
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX notifications_device_tokens_push_token ON notifications_device_tokens (push_token);
CREATE INDEX notifications_device_tokens_user_id ON notifications_device_tokens (user_id);
CREATE INDEX notifications_device_tokens_household_id ON notifications_device_tokens (household_id);

CREATE TABLE notifications_notification_log (
    id              TEXT    PRIMARY KEY,
    source_service  TEXT    NOT NULL,
    target_type     TEXT    NOT NULL, -- "user" | "household"
    target_id       TEXT    NOT NULL,
    title           TEXT    NOT NULL,
    body            TEXT    NOT NULL,
    data            TEXT,             -- JSON
    category        TEXT,
    token_count     INTEGER NOT NULL DEFAULT 0,
    success_count   INTEGER NOT NULL DEFAULT 0,
    failure_count   INTEGER NOT NULL DEFAULT 0,
    delivery_status TEXT    NOT NULL DEFAULT 'pending', -- pending|delivered|partial|failed|skipped
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX notifications_notification_log_source_service ON notifications_notification_log (source_service);
CREATE INDEX notifications_notification_log_target_id ON notifications_notification_log (target_id);

CREATE TABLE notifications_inbox_items (
    id             TEXT    PRIMARY KEY,
    user_id        INTEGER,
    household_id   TEXT    NOT NULL,
    title          TEXT    NOT NULL,
    summary        TEXT    NOT NULL,
    body           TEXT    NOT NULL,
    category       TEXT    NOT NULL,
    source_service TEXT    NOT NULL,
    metadata_json  TEXT,             -- JSON
    is_read        INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX notifications_inbox_items_user_id ON notifications_inbox_items (user_id);
CREATE INDEX notifications_inbox_items_household_id ON notifications_inbox_items (household_id);
CREATE INDEX notifications_inbox_items_category ON notifications_inbox_items (category);

-- +goose Down
DROP TABLE notifications_inbox_items;
DROP TABLE notifications_notification_log;
DROP TABLE notifications_device_tokens;
