package live

import (
	"encoding/json"
	"math"
	"os"
	"reflect"
	"sort"
	"testing"
)

// Goldens generated by running the frozen Python gateway (testdata/golden.json,
// testdata/system_prompt_*.txt, testdata/classifier.json).

type golden struct {
	Ratio     [][3]any    `json:"ratio"`
	Speech    [][2]string `json:"speech"`
	Mentions  [][3]any    `json:"mentions"`
	Verdict   [][3]any    `json:"verdict"`
	Farewell  [][2]any    `json:"farewell"`
	Time      [][2]any    `json:"time"`
	NonSpeech [][2]any    `json:"nonspeech"`
	Affirm    [][2]any    `json:"affirm"`
	Assess    [][3]any    `json:"assess"`
	Think     [][2]string `json:"think"`
	Sig       [][3]string `json:"sig"`
	TwiML     [][3]any    `json:"twiml"`
	MulawPCM  []int16     `json:"mulaw_pcm"`
	MulawEnc  []byte      `json:"mulaw_enc"`
	MulawDec  []int16     `json:"mulaw_dec"`
}

func loadGolden(t *testing.T) golden {
	t.Helper()
	b, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(b, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func TestGoldenSequenceRatio(t *testing.T) {
	for _, c := range loadGolden(t).Ratio {
		a, b, want := c[0].(string), c[1].(string), c[2].(float64)
		if got := SequenceRatio(a, b); math.Abs(got-want) > 1e-12 {
			t.Errorf("ratio(%.40q, %.40q) = %v, want %v", a, b, got, want)
		}
	}
}

func TestGoldenSpeech(t *testing.T) {
	for _, c := range loadGolden(t).Speech {
		if got := FormatForSpeech(c[0]); got != c[1] {
			t.Errorf("FormatForSpeech(%q) = %q, want %q", c[0], got, c[1])
		}
	}
}

func TestGoldenMentions(t *testing.T) {
	for _, c := range loadGolden(t).Mentions {
		if got := Mentions(c[0].(string), c[1].(string)); got != c[2].(bool) {
			t.Errorf("Mentions(%q, %q) = %v", c[0], c[1], got)
		}
	}
}

func TestGoldenVerdict(t *testing.T) {
	for _, c := range loadGolden(t).Verdict {
		got := ParseVerdict(c[0].(string), int(c[1].(float64)))
		var keys []int
		for k := range got {
			keys = append(keys, k)
		}
		sort.Ints(keys)
		var want []int
		for _, v := range c[2].([]any) {
			want = append(want, int(v.(float64)))
		}
		if !reflect.DeepEqual(keys, want) {
			t.Errorf("ParseVerdict(%q) = %v, want %v", c[0], keys, want)
		}
	}
}

func TestGoldenPredicates(t *testing.T) {
	g := loadGolden(t)
	check := func(name string, rows [][2]any, f func(string) bool) {
		for _, c := range rows {
			if got := f(c[0].(string)); got != c[1].(bool) {
				t.Errorf("%s(%q) = %v", name, c[0], got)
			}
		}
	}
	check("SoundsLikeFarewell", g.Farewell, SoundsLikeFarewell)
	check("MightProposeTime", g.Time, MightProposeTime)
	check("IsNonSpeech", g.NonSpeech, IsNonSpeech)
	check("IsAffirmation", g.Affirm, IsAffirmation)
}

func TestGoldenAssessment(t *testing.T) {
	for _, c := range loadGolden(t).Assess {
		summary, ga := ParseAssessment(c[0].(string))
		if summary != c[1].(string) {
			t.Errorf("summary(%q) = %q, want %q", c[0], summary, c[1])
		}
		switch want := c[2].(type) {
		case nil:
			if ga != nil {
				t.Errorf("goal(%q) = %v, want nil", c[0], *ga)
			}
		case bool:
			if ga == nil || *ga != want {
				t.Errorf("goal(%q) = %v, want %v", c[0], ga, want)
			}
		}
	}
}

func TestGoldenThink(t *testing.T) {
	for _, c := range loadGolden(t).Think {
		if got := StripThinkText(c[0]); got != c[1] {
			t.Errorf("StripThinkText(%q) = %q, want %q", c[0], got, c[1])
		}
	}
}

func TestGoldenTwilio(t *testing.T) {
	g := loadGolden(t)
	params0 := map[string]string(nil)
	if got := ComputeSignature(g.Sig[0][0], g.Sig[0][1], params0); got != g.Sig[0][2] {
		t.Errorf("signature = %q, want %q", got, g.Sig[0][2])
	}
	if got := ComputeSignature(g.Sig[1][0], g.Sig[1][1], map[string]string{"b": "2", "a": "1"}); got != g.Sig[1][2] {
		t.Errorf("signature with params = %q, want %q", got, g.Sig[1][2])
	}
	for _, c := range g.TwiML {
		var params [][2]string
		for _, kv := range c[1].([]any) {
			p := kv.([]any)
			params = append(params, [2]string{p[0].(string), p[1].(string)})
		}
		if got := StreamTwiML(c[0].(string), params); got != c[2].(string) {
			t.Errorf("TwiML = %q\nwant  %q", got, c[2])
		}
	}
}

func TestGoldenMulaw(t *testing.T) {
	g := loadGolden(t)
	if got := MulawEncode(g.MulawPCM); !reflect.DeepEqual(got, g.MulawEnc) {
		t.Error("MulawEncode differs from the Python codec")
	}
	all := make([]byte, 256)
	for i := range all {
		all[i] = byte(i)
	}
	if got := MulawDecode(all); !reflect.DeepEqual(got, g.MulawDec) {
		t.Error("MulawDecode differs from the Python codec")
	}
}

func TestGoldenSystemPrompt(t *testing.T) {
	briefs := []Brief{
		{Goal: "Order a large pie for pickup at 6", Details: "Order one large cheese pizza for pickup at 6pm.\nIf asked: name for the order is Alex.", InitiatorName: "Alex"},
		{Goal: "  Book a cleaning  ", Constraints: "Acceptable times: Tue 9am-noon\nDo not book: Wed 7am-5pm"},
	}
	for i, b := range briefs {
		want, err := os.ReadFile("testdata/system_prompt_" + string(rune('0'+i)) + ".txt")
		if err != nil {
			t.Fatal(err)
		}
		if got := BuildSystemPrompt(b); got != string(want) {
			t.Errorf("brief %d: system prompt differs from Python\n got: %q\nwant: %q", i, got, want)
		}
		wantD, _ := os.ReadFile("testdata/disclosure_" + string(rune('0'+i)) + ".txt")
		if got := BuildDisclosure(b); got != string(wantD) {
			t.Errorf("brief %d: disclosure = %q, want %q", i, got, wantD)
		}
		msgs := InitialMessages(b)
		if msgs[0][0] != "system" || msgs[1] != [2]string{"assistant", string(wantD)} {
			t.Errorf("InitialMessages = %v", msgs)
		}
	}
}

func TestGoldenClassifierMessages(t *testing.T) {
	b, err := os.ReadFile("testdata/classifier.json")
	if err != nil {
		t.Fatal(err)
	}
	var want [][2]string
	if err := json.Unmarshal(b, &want); err != nil {
		t.Fatal(err)
	}
	got := ClassifierMessages("what's your member ID?", []RestrictedField{
		{Key: "a", Label: "Insurance member ID", Value: "X"}, {Key: "b", Label: "Callback number", Value: "Y"},
	})
	if !reflect.DeepEqual(got, want) {
		t.Errorf("ClassifierMessages =\n%q\nwant\n%q", got, want)
	}
}
