-- Baseline: jarvis-auth at alembic head a1b2c3d4e5f6 (add signing_keys), translated from the
-- live dev DB on the MacBook Pro. See docs/schema/auth.md for type notes and import rules.
-- The settings table is created by internal/platform/settings (auth_settings), not here.
-- Timestamps are TEXT, ISO-8601 UTC. Every legacy timestamp in this DB was timestamptz.

-- +goose Up

-- AUTOINCREMENT: user ids are referenced by other modules without FKs (cc, notifications,
-- recipes), so an id must never be reused after a user is deleted.
CREATE TABLE auth_users (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    email                    TEXT    NOT NULL,
    username                 TEXT    NOT NULL,
    password_hash            TEXT    NOT NULL,
    is_active                INTEGER NOT NULL DEFAULT 1,
    is_superuser             INTEGER NOT NULL DEFAULT 0,
    must_change_password     INTEGER NOT NULL DEFAULT 0,
    temp_password_expires_at TEXT,
    created_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX auth_users_email ON auth_users (email);
CREATE UNIQUE INDEX auth_users_username ON auth_users (username);

CREATE TABLE auth_refresh_tokens (
    id         INTEGER PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
    token_hash TEXT    NOT NULL,
    expires_at TEXT    NOT NULL,
    revoked    INTEGER NOT NULL DEFAULT 0,
    created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    family_id  TEXT    NOT NULL, -- UUID, generated by the app
    parent_id  INTEGER REFERENCES auth_refresh_tokens (id) ON DELETE SET NULL,
    rotated_at TEXT
);
CREATE UNIQUE INDEX auth_refresh_tokens_token_hash ON auth_refresh_tokens (token_hash);
CREATE INDEX auth_refresh_tokens_user_id ON auth_refresh_tokens (user_id);
CREATE INDEX auth_refresh_tokens_family_id ON auth_refresh_tokens (family_id);
CREATE INDEX auth_refresh_tokens_family_revoked ON auth_refresh_tokens (family_id, revoked);
CREATE INDEX auth_refresh_tokens_parent_id ON auth_refresh_tokens (parent_id);

CREATE TABLE auth_app_clients (
    id              INTEGER PRIMARY KEY,
    app_id          TEXT    NOT NULL,
    name            TEXT    NOT NULL,
    key_hash        TEXT    NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_rotated_at TEXT
);
CREATE UNIQUE INDEX auth_app_clients_app_id ON auth_app_clients (app_id);

CREATE TABLE auth_households (
    id         TEXT PRIMARY KEY, -- UUID, generated by the app
    name       TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE auth_household_memberships (
    id           INTEGER PRIMARY KEY,
    household_id TEXT    NOT NULL REFERENCES auth_households (id) ON DELETE CASCADE,
    user_id      INTEGER NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
    role         TEXT    NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'power_user', 'admin')),
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (household_id, user_id)
);
CREATE INDEX auth_household_memberships_user_id ON auth_household_memberships (user_id);

CREATE TABLE auth_household_invites (
    id                 INTEGER PRIMARY KEY,
    household_id       TEXT    NOT NULL REFERENCES auth_households (id) ON DELETE CASCADE,
    code               TEXT    NOT NULL,
    created_by_user_id INTEGER REFERENCES auth_users (id) ON DELETE SET NULL,
    default_role       TEXT    NOT NULL DEFAULT 'member' CHECK (default_role IN ('member', 'power_user', 'admin')),
    max_uses           INTEGER,
    use_count          INTEGER NOT NULL DEFAULT 0,
    expires_at         TEXT    NOT NULL,
    revoked            INTEGER NOT NULL DEFAULT 0,
    created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX auth_household_invites_code ON auth_household_invites (code);
CREATE INDEX auth_household_invites_household_id ON auth_household_invites (household_id);
CREATE INDEX auth_household_invites_created_by_user_id ON auth_household_invites (created_by_user_id);

CREATE TABLE auth_node_registrations (
    id                    INTEGER PRIMARY KEY,
    node_id               TEXT    NOT NULL,
    node_key_hash         TEXT    NOT NULL,
    name                  TEXT    NOT NULL,
    is_active             INTEGER NOT NULL DEFAULT 1,
    household_id          TEXT    NOT NULL REFERENCES auth_households (id) ON DELETE CASCADE,
    registered_by_user_id INTEGER REFERENCES auth_users (id) ON DELETE SET NULL,
    created_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_rotated_at       TEXT
);
CREATE UNIQUE INDEX auth_node_registrations_node_id ON auth_node_registrations (node_id);
CREATE INDEX auth_node_registrations_household_id ON auth_node_registrations (household_id);
CREATE INDEX auth_node_registrations_registered_by_user_id ON auth_node_registrations (registered_by_user_id);

CREATE TABLE auth_node_service_access (
    id         INTEGER PRIMARY KEY,
    node_id    TEXT    NOT NULL REFERENCES auth_node_registrations (node_id) ON DELETE CASCADE,
    service_id TEXT    NOT NULL,
    granted_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    granted_by INTEGER REFERENCES auth_users (id) ON DELETE SET NULL,
    UNIQUE (node_id, service_id)
);
CREATE INDEX auth_node_service_access_service_id ON auth_node_service_access (service_id);
CREATE INDEX auth_node_service_access_granted_by ON auth_node_service_access (granted_by);

-- RS256 keypair (uncommitted WIP on the MBP checkout; see docs/schema/auth.md).
CREATE TABLE auth_signing_keys (
    id          INTEGER PRIMARY KEY,
    kid         TEXT    NOT NULL,
    algorithm   TEXT    NOT NULL DEFAULT 'RS256',
    private_pem TEXT    NOT NULL,
    public_pem  TEXT    NOT NULL,
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT             DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX auth_signing_keys_kid ON auth_signing_keys (kid);
CREATE INDEX auth_signing_keys_is_active ON auth_signing_keys (is_active);

-- +goose Down
DROP TABLE auth_signing_keys;
DROP TABLE auth_node_service_access;
DROP TABLE auth_node_registrations;
DROP TABLE auth_household_invites;
DROP TABLE auth_household_memberships;
DROP TABLE auth_households;
DROP TABLE auth_app_clients;
DROP TABLE auth_refresh_tokens;
DROP TABLE auth_users;
