-- Baseline: jarvis-recipes-server at alembic head e1f2a3b4c5d6, translated from the live dev DB
-- on the MacBook Pro. See docs/schema/recipes.md. The settings table is created by
-- internal/platform/settings (recipes_settings), not here.
-- Legacy timestamps were naive `timestamp` holding UTC; stored as ISO-8601 UTC TEXT.
-- `date` columns are TEXT 'YYYY-MM-DD'. json columns are TEXT. user_id is the auth user id
-- as a string (legacy convention, kept).

-- +goose Up

-- Shadow of auth users that own recipe data (legacy `users`, one column).
CREATE TABLE recipes_users (
    user_id TEXT PRIMARY KEY
);

CREATE TABLE recipes_recipes (
    id                 INTEGER PRIMARY KEY,
    user_id            TEXT    NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    household_id       TEXT,
    title              TEXT    NOT NULL,
    description        TEXT,
    image_url          TEXT,
    source_type        TEXT    NOT NULL DEFAULT 'manual' CHECK (source_type IN ('manual', 'image', 'url')),
    source_url         TEXT,
    servings           INTEGER,
    total_time_minutes INTEGER,
    created_at         TEXT             DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at         TEXT             DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX recipes_recipes_user_id ON recipes_recipes (user_id);
CREATE INDEX recipes_recipes_household_id ON recipes_recipes (household_id);

CREATE TABLE recipes_ingredients (
    id               INTEGER PRIMARY KEY,
    recipe_id        INTEGER NOT NULL REFERENCES recipes_recipes (id) ON DELETE CASCADE,
    text             TEXT    NOT NULL,
    quantity_display TEXT,
    quantity_value   REAL,   -- numeric(10,4)
    unit             TEXT
);
CREATE INDEX recipes_ingredients_recipe_id ON recipes_ingredients (recipe_id);

CREATE TABLE recipes_steps (
    id          INTEGER PRIMARY KEY,
    recipe_id   INTEGER NOT NULL REFERENCES recipes_recipes (id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    text        TEXT    NOT NULL,
    UNIQUE (recipe_id, step_number)
);

CREATE TABLE recipes_tags (
    id   INTEGER PRIMARY KEY,
    name TEXT    NOT NULL
);
CREATE UNIQUE INDEX recipes_tags_name ON recipes_tags (name);

CREATE TABLE recipes_recipe_tags (
    recipe_id INTEGER NOT NULL REFERENCES recipes_recipes (id) ON DELETE CASCADE,
    tag_id    INTEGER NOT NULL REFERENCES recipes_tags (id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, tag_id)
) WITHOUT ROWID;
CREATE INDEX recipes_recipe_tags_tag_id ON recipes_recipe_tags (tag_id);

CREATE TABLE recipes_meal_plans (
    id           INTEGER PRIMARY KEY,
    user_id      TEXT    NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    household_id TEXT,
    name         TEXT,
    start_date   TEXT    NOT NULL, -- YYYY-MM-DD
    created_at   TEXT             DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX recipes_meal_plans_user_id ON recipes_meal_plans (user_id);
CREATE INDEX recipes_meal_plans_household_id ON recipes_meal_plans (household_id);

CREATE TABLE recipes_meal_plan_items (
    id           INTEGER PRIMARY KEY,
    meal_plan_id INTEGER NOT NULL REFERENCES recipes_meal_plans (id) ON DELETE CASCADE,
    recipe_id    INTEGER NOT NULL REFERENCES recipes_recipes (id) ON DELETE CASCADE,
    date         TEXT    NOT NULL, -- YYYY-MM-DD
    meal_type    TEXT    NOT NULL
);
CREATE INDEX recipes_meal_plan_items_meal_plan_id ON recipes_meal_plan_items (meal_plan_id);
CREATE INDEX recipes_meal_plan_items_recipe_id ON recipes_meal_plan_items (recipe_id);

CREATE TABLE recipes_grocery_sku_map (
    id              INTEGER PRIMARY KEY,
    user_id         TEXT    NOT NULL,
    household_id    TEXT,
    retailer        TEXT    NOT NULL DEFAULT 'walmart',
    ingredient_name TEXT    NOT NULL,
    sku             TEXT    NOT NULL,
    product_name    TEXT,
    unit_size       TEXT,
    source          TEXT    NOT NULL DEFAULT 'manual',
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT
);
-- Same NULL semantics as Postgres: rows with a NULL household_id never collide.
CREATE UNIQUE INDEX recipes_grocery_sku_map_scope ON recipes_grocery_sku_map (household_id, user_id, retailer, ingredient_name);
CREATE INDEX recipes_grocery_sku_map_user_id ON recipes_grocery_sku_map (user_id);

CREATE TABLE recipes_recipe_parse_jobs (
    id               TEXT    PRIMARY KEY, -- UUID, generated by the app
    user_id          TEXT    NOT NULL,
    household_id     TEXT,
    job_type         TEXT    NOT NULL, -- url | ocr | social
    url              TEXT,
    use_llm_fallback INTEGER NOT NULL DEFAULT 1,
    status           TEXT    NOT NULL DEFAULT 'PENDING',
    result_json      TEXT,
    job_data         TEXT,
    error_code       TEXT,
    error_message    TEXT,
    attempts         INTEGER NOT NULL DEFAULT 0,
    started_at       TEXT,
    completed_at     TEXT,
    committed_at     TEXT,
    abandoned_at     TEXT,
    canceled_at      TEXT,
    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX recipes_recipe_parse_jobs_user_status ON recipes_recipe_parse_jobs (user_id, status);
CREATE INDEX recipes_recipe_parse_jobs_household_id ON recipes_recipe_parse_jobs (household_id);
CREATE INDEX recipes_recipe_parse_jobs_completed_at ON recipes_recipe_parse_jobs (completed_at);

CREATE TABLE recipes_recipe_ingestions (
    id                TEXT    PRIMARY KEY, -- UUID, generated by the app
    user_id           TEXT    NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    status            TEXT    NOT NULL DEFAULT 'PENDING',
    image_s3_keys     TEXT    NOT NULL, -- JSON array of blob keys
    selected_tier     INTEGER,
    tier_max          INTEGER,
    tier1_text        TEXT,
    tier2_text        TEXT,
    tier3_raw_response TEXT,            -- JSON
    pipeline_json     TEXT,             -- JSON
    title_hint        TEXT,
    recipe_id         INTEGER REFERENCES recipes_recipes (id) ON DELETE SET NULL,
    ocr_readings      TEXT,             -- JSON
    ocr_expected      INTEGER,
    ocr_joined_at     TEXT,
    created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX recipes_recipe_ingestions_user_id ON recipes_recipe_ingestions (user_id);
CREATE INDEX recipes_recipe_ingestions_recipe_id ON recipes_recipe_ingestions (recipe_id);

CREATE TABLE recipes_mailbox_messages (
    id         TEXT PRIMARY KEY, -- UUID, generated by the app
    user_id    TEXT NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    type       TEXT NOT NULL,
    payload    TEXT NOT NULL, -- JSON
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX recipes_mailbox_messages_user_id ON recipes_mailbox_messages (user_id);

CREATE TABLE recipes_stage_recipes (
    id                INTEGER PRIMARY KEY,
    user_id           TEXT    NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    title             TEXT    NOT NULL,
    description       TEXT,
    yield_text        TEXT,
    prep_time_minutes INTEGER DEFAULT 0,
    cook_time_minutes INTEGER DEFAULT 0,
    ingredients       TEXT    NOT NULL, -- JSON
    steps             TEXT    NOT NULL, -- JSON
    tags              TEXT    NOT NULL DEFAULT '[]', -- JSON
    notes             TEXT    NOT NULL DEFAULT '[]', -- JSON
    request_id        TEXT,
    created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at        TEXT    NOT NULL
);
CREATE INDEX recipes_stage_recipes_user_id ON recipes_stage_recipes (user_id);
CREATE INDEX recipes_stage_recipes_request_id ON recipes_stage_recipes (request_id);

CREATE TABLE recipes_staples (
    id           INTEGER PRIMARY KEY,
    user_id      TEXT    NOT NULL REFERENCES recipes_users (user_id) ON DELETE CASCADE,
    household_id TEXT,
    name         TEXT    NOT NULL,
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (user_id, name)
);
CREATE INDEX recipes_staples_household_id ON recipes_staples (household_id);

-- Reference data, seeded at runtime from static files (static_seed_service), not migrations.
CREATE TABLE recipes_stock_ingredients (
    id         INTEGER PRIMARY KEY,
    name       TEXT    NOT NULL,
    category   TEXT,
    synonyms   TEXT,
    created_at TEXT,
    updated_at TEXT
);
CREATE UNIQUE INDEX recipes_stock_ingredients_name ON recipes_stock_ingredients (name);

CREATE TABLE recipes_stock_units_of_measure (
    id           INTEGER PRIMARY KEY,
    name         TEXT    NOT NULL UNIQUE,
    abbreviation TEXT             UNIQUE,
    created_at   TEXT,
    updated_at   TEXT
);

-- +goose Down
DROP TABLE recipes_stock_units_of_measure;
DROP TABLE recipes_stock_ingredients;
DROP TABLE recipes_staples;
DROP TABLE recipes_stage_recipes;
DROP TABLE recipes_mailbox_messages;
DROP TABLE recipes_recipe_ingestions;
DROP TABLE recipes_recipe_parse_jobs;
DROP TABLE recipes_grocery_sku_map;
DROP TABLE recipes_meal_plan_items;
DROP TABLE recipes_meal_plans;
DROP TABLE recipes_recipe_tags;
DROP TABLE recipes_tags;
DROP TABLE recipes_steps;
DROP TABLE recipes_ingredients;
DROP TABLE recipes_recipes;
DROP TABLE recipes_users;
