// Command genrules writes ../../rules.go from the legacy Python's own strings, captured in
// fixtures/golden/prompts/_blocks.json (every str constant in core_rules) and _persona.json
// (persona_presets), so the rule text cannot drift by a typo. Run via go generate in the
// prompts package; rules_test.go proves the generated constants equal the fixtures.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	root := "../../../.."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	var blocks struct {
		Constants map[string]string `json:"constants"`
	}
	var persona struct {
		Frame     string `json:"PERSONA_FRAME"`
		Default   string `json:"DEFAULT_PERSONA"`
		MaxChars  int    `json:"PERSONA_MAX_CHARS"`
		DefaultID string `json:"DEFAULT_PERSONA_PRESET_ID"`
		Presets   []struct {
			ID    string `json:"id"`
			Label string `json:"label"`
			Text  string `json:"text"`
		} `json:"PERSONA_PRESETS"`
	}
	dir := filepath.Join(root, "fixtures", "golden", "prompts")
	load(filepath.Join(dir, "_blocks.json"), &blocks)
	load(filepath.Join(dir, "_persona.json"), &persona)

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/genrules from fixtures/golden/prompts/_blocks.json and\n")
	b.WriteString("// _persona.json (the legacy core_rules and persona_presets strings). DO NOT EDIT.\n\n")
	b.WriteString("package prompts\n\n")

	names := make([]string, 0, len(blocks.Constants))
	for k := range blocks.Constants {
		names = append(names, k)
	}
	sort.Strings(names)
	b.WriteString("// core_rules string constants, verbatim ({terminology} placeholders included).\nconst (\n")
	for _, k := range names {
		fmt.Fprintf(&b, "\t%s = %s\n\n", goName(k), literal(blocks.Constants[k]))
	}
	b.WriteString(")\n\n")

	b.WriteString("// Persona presets (services/persona_presets.py).\nconst (\n")
	fmt.Fprintf(&b, "\tPersonaFrame = %s\n\n", literal(persona.Frame))
	fmt.Fprintf(&b, "\tDefaultPersona = %s\n\n", literal(persona.Default))
	fmt.Fprintf(&b, "\tPersonaMaxChars = %d\n\n", persona.MaxChars)
	fmt.Fprintf(&b, "\tDefaultPersonaPresetID = %s\n", strconv.Quote(persona.DefaultID))
	b.WriteString(")\n\n")

	b.WriteString("// PersonaPresets are the mobile starter chips, in order.\nvar PersonaPresets = []PersonaPreset{\n")
	for _, p := range persona.Presets {
		text := literal(p.Text)
		if p.Text == persona.Default {
			text = "DefaultPersona"
		}
		fmt.Fprintf(&b, "\t{ID: %s, Label: %s, Text: %s},\n", strconv.Quote(p.ID), strconv.Quote(p.Label), text)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ruleConstants maps each Python constant name to its Go value (rules_test.go).\nvar ruleConstants = map[string]string{\n")
	for _, k := range names {
		fmt.Fprintf(&b, "\t%q: %s,\n", k, goName(k))
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("rules.go", src, 0o644); err != nil {
		fail(err)
	}
}

func load(path string, v any) {
	raw, err := os.ReadFile(path)
	if err != nil {
		fail(err)
	}
	if err := json.Unmarshal(raw, v); err != nil {
		fail(fmt.Errorf("%s: %w", path, err))
	}
}

// goName turns RULE_ONE_AT_A_TIME into RuleOneAtATime.
func goName(py string) string {
	var b strings.Builder
	for _, part := range strings.Split(strings.ToLower(py), "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

// literal renders s as a concatenation of quoted pieces broken after each newline and at
// spaces past ~90 bytes, so the generated file stays readable.
func literal(s string) string {
	var pieces []string
	cur := ""
	for _, r := range s {
		cur += string(r)
		if r == '\n' || (r == ' ' && len(cur) >= 90) {
			pieces = append(pieces, cur)
			cur = ""
		}
	}
	if cur != "" || len(pieces) == 0 {
		pieces = append(pieces, cur)
	}
	quoted := make([]string, len(pieces))
	for i, p := range pieces {
		quoted[i] = strconv.Quote(p)
	}
	return strings.Join(quoted, " +\n\t\t")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genrules:", err)
	os.Exit(1)
}
